### ISSUE TITLE
No package matching 'python3-pip' is available

### ISSUE THREAD

**Issue by y-temp4** [leesoh/ansible-role-pipenv#1]
Thank you for your great work! This role is very useful for me.

By the way, I got this error when I use ubuntu-xenial-16.04-amd64-server-20171121.1 (ami-bec974d8).

```
(item=python3-pip) => {"changed": false, "item": "python3-pip", "msg": "No package matching 'python3-pip' is available"}
```

But before [this](https://github.com/leesoh/ansible-role-pipenv/commit/f2de2883779402f22342c92fc31dc2e88fbb1781) commit, I can use this role.

I want to use this pipenv role for above version of ubuntu.

**Comment by leesoh** [comment]
That's interesting since the package name has remained the same (https://packages.ubuntu.com/search?keywords=python3-pip&searchon=names&suite=all&section=all). Can you install the package manually?

**Comment by y-temp4** [comment]
> That's interesting since the package name has remained the same (https://packages.ubuntu.com/search?keywords=python3-pip&searchon=names&suite=all&section=all). 

That is certainly true 😂

> Can you install the package manually?

I didn't try that, but I cloud install the package using following task.

```
---
- name: Get validator address
  shell: "cat {{ parity_keys_path }}/PrivateChain/{{ inventory_hostname }} | jq '.address' | sed 's/\"//g'"
  register: validator_address

- name: Add validator to config.toml
  lineinfile: >-
    dest='{{ parity_base_path }}/config.toml'
    state=present
    backrefs=yes
    regexp='^{{ item.key }}.*'
    line='{{ item.key }} = {{ item.value }}'
  with_items:
    - { key: 'engine_signer', value: '"0x{{ validator_address.stdout }}"' }

- name: Reload supervisor to start parity
  service: name=supervisor state=reloaded

- pause:
    minutes: 1

- name: enode tasks
  shell: "ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -f1 -d'/' | xargs echo"
  register: private_ips

- shell: "curl --data '{\"jsonrpc\":\"2.0\",\"method\":\"parity_enode\",\"params\":[],\"id\":0}' -H \"Content-Type: application/json\" -X POST {{ item }}:8545 | jq '.result'"
  register: enodes
  with_items: '{{ private_ips.stdout }}'

- file: path={{ parity_base_path }}/enode.sh state=touch owner=root group=root mode=0755

- lineinfile:
    dest: '{{ parity_base_path }}/enode.sh'
    line: "curl --data '{\"jsonrpc\":\"2.0\",\"method\":\"parity_addReservedPeer\",\"params\":[{{ item }}],\"id\":0}' -H \"Content-Type: application/json\" -X POST localhost:8545"
  with_items:
    - '{{ enodes.results[0].stdout }}'

- name: Install lsyncd
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - lsyncd

- name: Change permissions for keys directory
  file: path="{{ parity_keys_path }}" state=directory mode=755 owner=ubuntu group=ubuntu recurse=yes

- name: Add directory for lsyncd config
  file: path=/etc/lsyncd state=directory owner=root group=root mode=0755

- name: Add lsyncd config
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { src: 'lsyncd.conf.lua.j2', dest: '/etc/lsyncd/lsyncd.conf.lua' }

- name: Add lsyncd config for supervisor
  template: src={{ item.src }} dest=/etc/supervisor/conf.d/{{ item.dest }} backup=yes
  with_items:
    - { src: 'lsync.conf.j2', dest: 'lsync.conf' }

- name: Change account refresh time to 5 sec
  lineinfile: >-
    dest='{{ parity_base_path }}/config.toml'
    state=present
    backrefs=yes
    regexp='^{{ item.key }}.*'
    line='{{ item.key }} = {{ item.value }}'
  with_items:
    - { key: 'refresh_time', value: '5' }

- name: Reload supervisor to start lsync
  service: name=supervisor state=reloaded

- pause:
    seconds: 10

- name: And restart lsync to fix startup problem.
  command: /etc/init.d/lsyncd restart
```
